---
title: "Factorizacion LU"
author: "Oscar Omar"
date: "17/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(matlib)
require(reticulate)
```

## Ejemplo 1 en `R`
```{r}
A = rbind(c(1,3,0,-1),c(2,1,-1,5),c(0,-2,3,-1),c(1,1,3,1))
A
lua = LU(A)
lua
lua$L %*% lua$U 
```

## Ejemplo 2 en `R`
```{r}
A = matrix(c(0,1,3,1,3,-2,-3,-2,-1), byrow = T, nrow = 3, ncol = 3)
A
lua = LU(A)
lua
lua$L %*% lua$U 
```

## Ejemplo 3 en `R`
```{r}
A = rbind(c(0,1,3),c(1,3,-2),c(3,-2,-1))
b = c(1,3,-2)
lua = LU(A,b)
lua
```

## Ejemplo 1 en `PYTHON`
```{python}
import scipy
import scipy.linalg
A = scipy.array([[1,3,0,-1],[2,1,-1,5],[0,-2,3,-1],[1,1,3,1]])
P,L,U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
```

## Ejemplo 2 en `PYTHON`
```{python}
import scipy
import scipy.linalg
A = scipy.array([[0,1,3],[1,3,-3],[-1,-2,-3,]])
P,L,U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
```

## Ejemplo 3 en `PYTHON`
```{python}
import scipy
import scipy.linalg
A = scipy.array([[0,1,3],[1,3,-3],[-1,-2,-3,]])
LU, piv = scipy.linalg.lu_factor(A)
print(LU)
print(U)
print(L)
print(piv)
```

## Ejemplo 4 en `PYTHON`
```{python}
import scipy
import scipy.linalg
A = scipy.array([[0,1,3],[1,3,-3],[-1,-2,-3,]])
LU, piv = scipy.linalg.lu_factor(A)
b = [1,3,-2]
x = scipy.linalg.lu_solve((LU,piv), b)
x
```



