---
title: "ejercicios_ecuaciones_lineales"
author: "Oscar Omar"
date: "12/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(matlib)
```

```{r}
A <- rbind(c(1,1,2),c(2,4,-3),c(3,6,-5))
b <- c(9,1,0)
AB <- cbind(A,b)
AB
qr(A)$rank==qr(AB)$rank
solve(A,b)
```
## Ejemplo 2 en `R`
```{r}
A <- rbind(c(2,2),c(-1,1))
b <- c(1,2)
AB <- cbind(A,b)
R(A)
R(AB)
Solve(A, b, fractions = TRUE)
plotEqn(A,b)
points(-3/4,5/4, col="turquoise1", pch=19)
```
## Ejemplo 3 en `R`

```{r}
A <- rbind(c(4,2),c(1,-2),c(3,4))
b <- c(3,2,1)
AB <- cbind(A,b)
showEqn(A,b)
R(A)
R(AB)
all.equal(R(A),R(AB))
Solve(A,b, fractions = T)
s = c(1, -1/2)
A%*%s == b
plotEqn(A,b)
```

```{r}
A <- rbind(c(1,1,2),c(2,4,-3),c(3,6,-5))
b <- c(9,1,0)
AB <- cbind(A,b)
AB
qr(A)$rank==qr(AB)$rank
solve(A,b)
echelon(AB, verbose = T, fractions = T)
```

```{r}
a <- matrix(c(1,1,-1,1,-1,1,3,1,-1), byrow = TRUE, nrow = 3, ncol = 3)
b <- c(2,1,5)
ab = cbind(a,b)
c(R(a),R(ab))
echelon(ab)
Solve(a,b, fractions = T)
```

```{r}
A <- cbind(c(1,1,2),c(1,-1,1))
b <- c(2,1,3)
AB <- cbind(A,b)
AB
c(R(A), R(AB))
Solve(A,b, fractions = T)
all.equal(R(A), R(AB))
echelon(AB)
plotEqn(A,b)
```
## Ejemplo 6 `R`
```{r}
A <- rbind(c(0,4),c(2,1))
B <- rbind(c(1,-1),c(2,3))
C <- rbind(c(1,2),c(3,-2))
D <- rbind(c(-2,1),c(-1,1))
I <- diag(1, nrow = 2, ncol = 2)
M <- A - (C + D)
N <- 3*(D-B)+10*I
X <- solve(M,N)
X
A%*%X + 3*B == (C+D)%*%X+3*D+10*I
```

## Ejemplo 1 `Python`
```{python}
import numpy as np
A = np.array([[1,1,2],[2,4,-3],[3,6,-5]])
b = np.array([9,1,0])
AB = np.array([[1,1,2,9],[2,4,-3,1],[3,6,-5,0]])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)
np.linalg.matrix_rank(A)
np.linalg.solve(A, b)
```

## Ejemplo 2 `Python`
```{python}
from sympy import *
from sympy.solvers.solveset import linsolve
x,y,z = symbols('x,y,z')
x1,x2,x3 = symbols('x1,x2,x3')
linsolve([2*x1 + 2*x2 - 1, -x1 + x2 - 2], (x1,x2))
linsolve(Matrix(([2,2,1],[-1,1,2])), (x1,x2))
import matplotlib.pyplot as plt
x1 = np.linspace(0,10,100)
plt.plot(x1, 1/2-x1, x1, (2+x1)/4)
plt.show()
```

## Ejemplo 3 `Python`
```{python}
import matplotlib.pyplot as plt
x1 = np.linspace(0,10,100)
plt.plot(x1, 3/2-2*x1, x1, (x1/2)-1, x1, (1-3*x1)/4)
plt.show()
```

## Ejemplo 4 `Python`
```{python}
from mpl_toolkits.mplot3d import Axes3D

point1 = np.array([0,0,9/2])
n1 = np.array([1,1,2])

point2 = np.array([0,0,-1/3])
n2 = np.array([2,4,-3])

point3 = np.array([0,0,0])
n3 = np.array([3,6,-5])

D1 = -9
D2 = -1
D3 = 0

X, Y = np.meshgrid(range(30), range(30))

Z1 = (-n1[0]*X - n1[1]*Y - D1)*1./n1[2]
Z2 = (-n2[0]*X - n2[1]*Y - D2)*1./n2[2]
Z3 = (-n3[0]*X - n3[1]*Y - D3)*1./n3[2]

plot3d = plt.figure().gca(projection='3d')
plot3d.plot_surface(X,Y,Z1, color='red')
plot3d.plot_surface(X,Y,Z2, color='cyan')
plot3d.plot_surface(X,Y,Z3, color='yellow')
plt.show()
```

## Ejemplo 5 `Python`
```{python}
A = np.array([[1,1,-1],[1,-1,1],[3,1,-1]])
B = np.array([2,1,5])
AB = np.array([[1,1,-1,2],[1,-1,1,1],[3,1,-1,5]])

np.linalg.matrix_rank(A)
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)

point1 = np.array([0,0,-2])
n1 = np.array([1,1,-1])

point2 = np.array([0,0,1])
n2 = np.array([1,-1,1])

point3 = np.array([0,0,-5])
n3 = np.array([3,1,-1])

#Terminos independientes
D1 = -2
D2 = -1
D3 = -5

#Se crea la matriz de cooordenandas

X, Y = np.meshgrid(range(-20,20), range(30))

Z1 = (-n1[0]*X - n1[1]*Y - D1)*1./n1[2]
Z2 = (-n2[0]*X - n2[1]*Y - D2)*1./n2[2]
Z3 = (-n3[0]*X - n3[1]*Y - D3)*1./n3[2]

plot3d = plt.figure().gca(projection='3d')
plot3d.plot_surface(X,Y,Z1, color='red')
plot3d.plot_surface(X,Y,Z2, color='cyan')
plot3d.plot_surface(X,Y,Z3, color='yellow')
plt.show()

linsolve([x + y - z - 2, x - y + z - 1, 3*x + y - z - 5], (x,y,z))

```

## Ejemplo 6 `Python`
```{python}
A = np.array([[1,1],[1,-1],[2,1]])
b = np.array([2,1,3])
AB = np.array([[1,1,2],[1,-1,1],[2,1,3]])
np.linalg.matrix_rank(A)
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(AB)

linsolve(Matrix(([1,1,2],[1,-1,1],[2,1,3])), (x,y))

x1 = np.linspace(-1,2,100)
plt.plot(x1, 2 - x1, x1, x1 - 1, x1, 3 - 2*x1)
plt.show()
```