---
title: "Vectores"
author: "Oscar Omar"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(matlib)
require(pracma)
require(reticulate)
```


```{r include=FALSE}
###### Funciones en R #######
productoEscalar = function(x,y){
  if(length(x) == length(y)){
    sum(x*y)
  }else {
    print("ERROR: No se puede calcular el producto escalar de estos dos vectores porque no son de la misma dimension")
  }
}

normaVector = function(x){
  sqrt(productoEscalar(x,x))
}

distancia = function(x,y){
  if(length(x) == length(y)){
    Norm(x-y)
  }else {
    print("ERROR: No se puede calcular el producto escalar de estos dos vectores porque no son de la misma dimension")
  }
}


angleRad = function(x,y){
  if(length(x) == length(y)){
    acos(productoEscalar(x,y)/Norm(x)*Norm(y))
  }else {
    print("ERROR: No se puede calcular el producto escalar de estos dos vectores porque no son de la misma dimension")
  }
}

angleGrad = function(x,y){
  if(length(x) == length(y)){
    acos(productoEscalar(x,y)/(Norm(x)*Norm(y)))*360/(2*pi)
  }else {
    print("ERROR: No se puede calcular el producto escalar de estos dos vectores porque no son de la misma dimension")
  }
}

proyeccionOrt = function(x,y){
  if(length(x) == length(y)){
    productoEscalar(x,y)/Norm(x)^2*x
  }else {
    print("ERROR: No se puede calcular el producto escalar de estos dos vectores porque no son de la misma dimension")
  }
}

productoVectorial = function(x,y){
  if(length(x) == length(y) & length(x) == 3){
    c(x[2]*y[3] - x[3]*y[2], x[1]*y[3] - x[3]*y[1], x[1]*y[2] - x[2]*y[1])
  }else {
    print("No se cumplen las condiciones necesarias paracalcular el producto vectorial de estos dos vetores")
  }
}

productoMixto = function(x,y,z){
  if(length(x) == length(y) & length(x) == length(z) & length(x) == 3){
    det(rbind(x,y,z))
  }else {
    print("No se cumplen las condiciones necesarias para calcular el producto mixto de los tres vectores")
  }
}

```

## Producto Escalar con `R`
```{r}

x = c(0,3,-1,3,5)
y = c(1,2,3,-1,0)
productoEscalar(x,y)
```

## Norma con `R`
```{r}

x = c(1,2,0,3,-1,1.8,9)
Norm(x)

normaVector(x)

```

## Distancia de dos puntos con `R`
```{r}

x = c(0,3,-1,3,5)
y = c(1,2,3,-1,0)

distancia(x,y)
angleRad(x,y)
angleGrad(x,y)
```

## proyeccion ortogonal con `R`
```{r}

x = c(3,1)
y = c(1,2)

proyeccionOrt(x,y)
proyeccionOrt(y,x)

```

## Producto Vectorial con `R`
```{r}

x = c(1,2,3)
y = c(0,-1,1)

productoVectorial(x,y)

```

## Producto mixto con `R`
```{r}

x = c(1,2,3)
y = c(0,-1,1)
z = c(2,0,-3)

productoMixto(x,y,z)

```

```{python include=FALSE}
import numpy as np
def productoEscalar(x,y):
  import numpy as np
  if len(x) == len(y):
    suma = 0
    for i in range(0, len(x)):
      suma = suma + x[i]*y[i]
    return suma
  else:
    return "Error: las longitudes de los vectores no coinciden"

def distancia(x,y):
  import numpy as np
  if len(x) == len(y):
    dist = np.linalg.norm(x-y)
    return dist
  else:
    return "Error: las longitudes de los vectores no coinciden"
  
def angleRad(x,y):
  import numpy as np
  import math
  if len(x) == len(y):
    angle = math.acos(productoEscalar(x,y)/(np.linalg.norm(x)*np.linalg.norm(y)))
    return angle
  else:
    return "ERROR: las dimenciones no coinciden"
  
def angleGrad(x,y):
  import numpy as np
  import math
  if len(x) == len(y):
    angle = math.acos(productoEscalar(x,y)/(np.linalg.norm(x)*np.linalg.norm(y)))
    return angle/(2*math.pi)*360
  else:
    return "ERROR: las dimenciones no coinciden"

def proyeccionOrt(x,y):
  import numpy as np
  if len(x) == len(y):
    proy = (productoEscalar(x,y)/pow(np.linalg.norm(x),2))*x
    return proy
  else:
    return "ERROR: las dimenciones no coinciden"

def productoVectorial(x,y):
  import numpy as np
  if len(x) == len(y) and len(x) == 3:
    z = np.array([x[1]*y[2] - x[2]*y[1], -(x[0]*y[2] - x[2]*y[0]), x[0]*y[1] - x[1]*y[0]])
    return z
  else:
    return "Error"
  
def productoMixto(x,y,z):
  import numpy as np
  if len(x) == len(y) and len(x) == len(z) and len(z) == 3:
    return np.linalg.det(np.array([x,y,z]))
  else:
    return "Error"

```

## Producto Escalar con `PYTHON`
```{python}
x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
productoEscalar(x,y)
```


## Norma con `PYTHON`
```{python}
x = np.array([1,2,0,3,-1,1])
np.linalg.norm(x)
```

## Distancia de dos puntos con `PYTHON`
```{python}
x = np.array([0,3,-1,3,5])
y = np.array([1,2,3,-1,0])
distancia(x,y)
angleRad(x,y)
angleGrad(x,y)
```

## proyeccion ortogonal con `PYTHON`
```{python}
x = np.array([3,1])
y = np.array([1,2])
proyeccionOrt(x,y)
```

## Producto Vectorial con `PYTHON`
```{python}
x = np.array([1,2,3])
y = np.array([0,-1,1])
productoVectorial(x,y)
```

## Producto mixto con `PYTHON`
```{python}
x = np.array([1,2,3])
y = np.array([0,-1,1])
z = np.array([2,0,-3])
productoMixto(x,y,z)

```
